### ISSUE TITLE
parse_url import error

### ISSUE THREAD

**Issue by elundmark** [y0ssar1an/CSS3#25]
I noticed this error in the console:
```
reloading plugin CSS3.validator
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "validator in /home/elundmark/.config/sublime-text-3/Installed Packages/CSS3.sublime-package", line 1, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "requests in /home/elundmark/.config/sublime-text-3/Installed Packages/CSS3.sublime-package", line 59, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "requests.models in /home/elundmark/.config/sublime-text-3/Installed Packages/CSS3.sublime-package", line 21, in <module>
ImportError: cannot import name parse_url
```
_ST3 build 3083 Linux (xubuntu 14.10 64-bit)_

**Comment by y0ssar1an** [comment]
I can't reproduce the issue, but I have some guesses about what's causing the problem. CSS3 uses the popular [`requests`](http://docs.python-requests.org/en/latest/) module, which uses `urllib3` internally. Importing the `urllib3` function `parse_url()` is what's raising the exception.

![image](https://cloud.githubusercontent.com/assets/1250684/7339894/3647e1e0-ec33-11e4-9fd4-6ea5c156d694.png)

That `ImportError` is usually caused by a circular import, which to me suggests a conflict with another package. That comment in the code about overlapping the Python stdlib `urlparse` is also troubling.

I'm not sure what's causing the problem, but as a shot in the dark I've upgraded requests to version 2.6.2 and changed the way I'm importing it into the validator. I'll push out the update shortly. Please let me know if the problem persists.

**Comment by elundmark** [comment]
Great stuff, I'll check again once I get the update. I did however upgrade to xubuntu 15.04 today, so it won't really be a fair comparison, I'm guessing a whole bunch of my python packages have been upgraded...

**Comment by y0ssar1an** [comment]
I haven't heard any more reports of this issue, so I'm closing it. I will reopen if anyone else reports the issue.
